# Generated by Django 3.1.2 on 2020-10-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='category',
            field=models.CharField(blank=True, default='blank', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='unit',
            field=models.CharField(blank=True, default='piece', max_length=30),
            preserve_default=False,
        ),
    ]
