# Generated by Django 3.1.2 on 2020-10-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_auto_20201013_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='listitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
